name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [ push ]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup python3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install formatter
        run: |
          python -m pip install black isort mypy

      - name: Run formatters
        run: |
          black 01_advanced_basics/homework/log_analyzer.py
          isort 01_advanced_basics/homework/log_analyzer.py
          mypy 01_advanced_basics/homework/log_analyzer.py

      - name: Run tests
        run:
          python 01_advanced_basics/homework/tests.py
